name: Checks · Lint
run-name: "Checks · Lint · ${{ github.event_name }} · ${{ github.sha }}"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    uses: grootan-devops/github-ci-library/.github/workflows/lint.yml@1.0.0
    permissions:
      contents: read
    secrets: inherit
    with:
      lint-md-files: "**/*.md"
