name: Security · Secret Scan
run-name: "Security · Secret Scan · ${{ github.event_name }} · ${{ github.sha }}"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  secret-scan:
    uses: grootan-devops/github-ci-library/.github/workflows/secret-scanning.yml@1.0.0
    permissions:
      contents: read
    secrets: inherit
    with:
      full-history: true
